name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: idris-lang/idris2
          path: idris2
      - name: install idris2api
        run: |
          cd idris2 && make install-api
        shell: bash
      - name: build and test
        run: |
          make build && make test INTERACTIVE=''
        shell: bash
